apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchvision
  labels:
    app: torchvision
spec:
  selector:
    matchLabels:
      app: torchvision
  template:
    metadata:
      labels:
        app: torchvision
    spec:
      containers:
      - image: mispicer/modelfoundrypublic:torchvision_custom
        name: torchvision
